#!/bin/bash
# This script removes the soft links to CodeAnalyzer's C/C++ compiler wrappers
# in the ~/tools directory, so that the original C/C++ compilers will be used
# afterwards.
#
rm -f ~/bin/cc
rm -f ~/bin/gcc
rm -f ~/bin/g++
rm -f ~/bin/c++

